/**
 * Automatic import handling: read the `import` statements in Elm source, work
 * out which packages provide them, and install whatever is missing.
 *
 * The mapping from module to package comes from `elm-modules-index.json`
 * (generated by `scripts/build-module-index.mjs`), because neither the Elm
 * compiler nor package.elm-lang.org exposes it at runtime.
 */
import { installPackages } from './packages.js';
import { getSources } from './sources.js';

/** Remove line and block comments so `import` inside them is ignored. */
const stripComments = (source) => source.replace(/\{-[\s\S]*?-\}/g, ' ').replace(/--[^\n]*/g, ' ');

/**
 * Module names imported by Elm source, in source order.
 * Handles `import Html`, `import Html.Attributes as A`, `import X exposing (..)`.
 */
export function detectImports(source) {
  const modules = new Set();
  const re = /^[ \t]*import[ \t]+([A-Z][\w]*(?:\.[A-Z][\w]*)*)/gm;
  let match;
  while ((match = re.exec(stripComments(source))) !== null) modules.add(match[1]);
  return [...modules];
}

/**
 * Work out which of `imports` are not yet available and which package provides
 * each one.
 *
 * @param {object} options
 * @param {string[]} options.imports        module names
 * @param {Set<string>} options.available   modules already provided by installed packages
 * @param {Record<string, [string, string]>} [options.index]  module -> [package, version]
 */
export function resolveImports({ imports, available, index }) {
  const needed = [];
  const unresolved = [];
  for (const moduleName of imports) {
    if (available.has(moduleName)) continue;
    const entry = index?.[moduleName];
    if (entry) needed.push({ module: moduleName, package: entry[0], version: entry[1] });
    else unresolved.push(moduleName);
  }
  return { needed, unresolved };
}

/**
 * Detect the imports in `source` and install any missing packages.
 *
 * @returns {Promise<{ imports: string[], installed: string[], unresolved: string[] }>}
 */
export async function autoInstallImports(compiler, source, { index, cdn, sources = getSources(cdn), log = () => {} } = {}) {
  const imports = detectImports(source);
  const available = compiler.listModules();
  const { needed, unresolved } = resolveImports({ imports, available, index });

  const specs = [...new Set(needed.map(({ package: pkg, version }) => `${pkg}@${version}`))];
  if (specs.length) await installPackages(compiler, specs, { sources, log });

  return { imports, installed: specs, unresolved };
}
